apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20% 
      maxSurge: 20% 
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      securityContext:
        # k8s 1.31 이상 지원
        allowPrivilegeEscalation: false 

# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
